### ISSUE TITLE
Unable to get custom resource pack to work (Very Confused, Please Help)

### ISSUE THREAD

**Issue by drdinguspingus** [Roundaround/mc-fabric-custom-paintings-noui#2]
I downloaded your famous paintings pack as a base and then edited it. I swear I've checked this a million times, but my pack does not work with the mod for some reason. I thought it could be the size of the images since they're bigger, but it's not. I re-added the Mona Lisa, but she didn't show up. After general checks with names and stuff, it still doesn't work. I even re-enabled the famous paintings pack, which worked fine; I'm confused and tired. Please, help me.

I've added the zip if you need it. It was a lot more customized, but I ripped only the essentials and shoved it into the famous paintings pack as one last-ditch effort.

~~Famous Paintings 1.20.zip~~ _(file link removed due to 18+ content)_
(Again, edited)

**Comment by Roundaround** [comment]
Hello! It looks like your custompaintings.json is missing a closing double quote (") on like 42, which makes the JSON malformed. Adding that in fixes it. From what I can tell, everything else is valid!

**Comment by drdinguspingus** [comment]
Thank you so much; I'm glad to have these custom paintings. Have a good day!
